### ISSUE TITLE
No organizations and frozen mqtt client on TI Launchpad

### ISSUE THREAD

**Issue by benjaminchodroff** [ibm-messaging/iotf-rtd#14]
I have signed up for the IoT Foundation through bluemix, but when I login and then click the person icon here:
https://internetofthings.ibmcloud.com/

I see "Your Organizations (0)" "You are not a member of any organization"

I went ahead and made up an organization "test"

When I try running the sample MQTT client in Energia using a TI Launchpad 5529 and a wifi CC3100BOOST, it freezes up when it reaches the line "while ((rc = client.connect(connectData)) != 0);"

**Comment by benjaminchodroff** [comment]
My bluemix expired. Switched a new account, got an organization code, but the code still locks up here:
"while ((rc = client.connect(connectData)) != 0);"

**Comment by ValerieLampkin** [comment]
Was this ever working?  If you email your org to me, I can check logs to help troubleshoot.

**Comment by benjaminchodroff** [comment]
Turns out my bluemix expired, I have another account now and it's working fine. Thanks!
