### ISSUE TITLE
Break up Device-Operations-Reference.rst

### ISSUE THREAD

**Issue by durera** [ibm-messaging/iotf-rtd#22]
I think it would be better if this were three pages, it's currently a lot to take in and really doesn't allow us to break down DM into the three parts that you can choose to implement (or not).

1. Device Management - Basic Operations (baseline operations that should be supported by most DM capable devices)
2. Device Management - Firmware Actions (if device has mgmt.supports.firmwareActions)
3. Device Management - Device Actions (if device has mgmt.supports.firmwareActions)

**Comment by EdProsser** [comment]
Sounds like a good plan to me, I'll start making these changes soon.

**Comment by durera** [comment]
iotf-rtd/docs/device management/actions.rst

This page has a perfect breakdown of operation by type (management, device attributes, device actions, firmware actions etc) .. 

Let's have a reference page per each type on that page.

dm/operations/index.rst
dm/operations/management.rst
dm/operations/attributes.rst
dm/operations/deviceactions.rst
dm/operations/firmwareactions.rst

etc

on the firmwareactions and deviceactions we also need to mention that these features require the device to set mgmt.supports.deviceActions or mgmt.supports.deviceActions to True.

**Comment by durera** [comment]
Changes in https://github.com/ibm-messaging/iotf-rtd/commit/0e78284cc0b05822e40d77149f228b5dabfae417 address this
