### ISSUE TITLE
actions_firmware.rst examples need cleaning up

### ISSUE THREAD

**Issue by durera** [ibm-messaging/iotf-rtd#24]
This page is all about firmware updates: docs/device management/actions_firmware.rst

However, the examples contain other actions ... those examples may need moving to another page, or may be duplicates...

**Comment by EdProsser** [comment]
This is the doc I'm working on at the moment.

**Comment by durera** [comment]
Changes in https://github.com/ibm-messaging/iotf-rtd/commit/0e78284cc0b05822e40d77149f228b5dabfae417 merged the two seperate firmware documents into a single doc and all the rogue examples were removed earlier
