### ISSUE TITLE
API Section needs to include base URL and how to obtain credentials

### ISSUE THREAD

**Issue by uwefassnacht** [ibm-messaging/iotf-rtd#30]
Its not obvious which base-URL to use for the API. 

I observed developers struggling until they finally understood that the base URL is something like:
https://xxxxxx.internetofthings.ibmcloud.com:443/api/v0002

The base URL needs to be clearly explained in the intro section for the API. Ideally with a few examples. Those examples should also illustrate:

- where to obtain the IoTF org (needed for the base URL)
- how to authenticate with the API (including an example)
- where to obtain the authorization credentials (API key and auth token)

Some of that information is available here: https://developer.ibm.com/iotfoundation/recipes/api-documentation/ but needs to be included in this doc as well.

**Comment by durera** [comment]
This has been updated in the IoTF swagger specs (which aren't in the github repo so I can't tag a commit to this) .. attaching image of the additional description that will be available in the swagger generated docs at next update:

![description](https://cloud.githubusercontent.com/assets/4400618/12684138/0acc6704-c6b5-11e5-8845-890e68e3f786.jpg)

**Comment by uwefassnacht** [comment]
Thanks David!
