### ISSUE TITLE
Node.js sample code needs to include error handling

### ISSUE THREAD

**Issue by uwefassnacht** [ibm-messaging/iotf-rtd#31]
Took me a while to understand how errors are emitted and how to handle them. Would be good to include a brief section on error handling, maybe with sample code similar to this:

```
// Handle errors coming from the IoT Foundation service
iotfClient.on("error", function (err) {
    console.log("Error received from IoTF service: " + err.message);
    }
});

```

**Comment by jeffdare** [comment]
Hi,
The error handling is included in the documentation now.

**Comment by jeffdare** [comment]
This is fixed. Closing the issue.

**Comment by HNorlen** [comment]
Verified in migrated docs as well:
https://new-console.stage1.ng.bluemix.net/docs/services/IoT/applications/libraries/nodejs.html
https://new-console.stage1.ng.bluemix.net/docs/services/IoT/devices/libraries/nodejs.html
