### ISSUE TITLE
Client.parseConfigFile(configFilePath) doesn't work

### ISSUE THREAD

**Issue by neckert** [ibm-messaging/iotf-rtd#32]
Most of the samples for Node.js call Client.parseConfigFile() to retrieve the configuration from a configuration file. When I tried this, an exception occurred stating that the function is undefined. I checked the code (ibmiotf node module, version 0.2.10) and couldn't find the parseConfigFile method, which explains why it didn't work.

**Comment by anpross** [comment]
did run into the same issue - here is the doc that mentions the non-existing function: https://docs.internetofthings.ibmcloud.com/applications/libraries/nodejs.html

**Comment by jeffdare** [comment]
Hi,
I have updated the documentation on how to use the config json file. Please verify.
Thanks!

**Comment by anpross** [comment]
same as with the other issue, second heading still reads "Using a configuration file". cleared browser cache etc.

**Comment by anpross** [comment]
git change looks fine - its just not published yet.

**Comment by jeffdare** [comment]
Its updated in the doc page now. The doc page refreshes daily once. :) Hence the delay.

**Comment by jeffdare** [comment]
This issue is fixed. Hence closing.
