### ISSUE TITLE
"Publishing events from devices" sample broken

### ISSUE THREAD

**Issue by anpross** [ibm-messaging/iotf-rtd#40]
the sample shows that a Object named "myData" is passed. However this needs to be a String
`Connection Error :: TypeError: Argument must be a string
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Argument must be a string
    at TypeError (native)
    at Buffer.write (buffer.js:429:18)`

also found this issue on the iot-nodejs project confirming this: 
https://github.com/ibm-messaging/iot-nodejs/issues/9

**Comment by jeffdare** [comment]
Thanks for pointing out. I have updated the documentation.

**Comment by anpross** [comment]
any special publishing involved? i dont see it updated here: https://docs.internetofthings.ibmcloud.com/applications/libraries/nodejs.html#/publishing-events-from-devices#publishing-events-from-devices

**Comment by anpross** [comment]
ok, i checked the git change and that look fine.
